# Generated by Django 4.0 on 2022-02-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0006_alter_product_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.IntegerField(default=1),
        ),
    ]
